---
creation_rules:
  - path_regex: secrets/.+\.sops\.yaml.j2
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1tkqegngtmhgcqqjcxwf58quer37r400dy8mn9t29mg2ngse2uvfq6zd856"
  - path_regex: secretss/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1tkqegngtmhgcqqjcxwf58quer37r400dy8mn9t29mg2ngse2uvfq6zd856"
