---
creation_rules:
  - path_regex: kubernetes/.+\.sops\.yaml.j2
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1x67hs2jznngs2kc7wpctemewlps0qw6pcyayf4d9tvhyvvrkgu7sqz4wd2"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1x67hs2jznngs2kc7wpctemewlps0qw6pcyayf4d9tvhyvvrkgu7sqz4wd2"

  - path_regex: terraform/.*\.sops\.env
    key_groups:
      - age:
          - "age1x67hs2jznngs2kc7wpctemewlps0qw6pcyayf4d9tvhyvvrkgu7sqz4wd2"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1x67hs2jznngs2kc7wpctemewlps0qw6pcyayf4d9tvhyvvrkgu7sqz4wd2"
