---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"
  # Binaries
  PYTHON_BIN: python3

env:
  PYTHONDONTWRITEBYTECODE: "1"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  repository: .taskfiles/Repository
  sops: .taskfiles/Sops
  workstation: .taskfiles/Workstation
  user:
    taskfile: .taskfiles/User
    optional: true

tasks:

  default: task --list

  .validate:
    internal: true
    cmds:
      - cmd: |
          if [[ $SOPS_AGE_KEY_FILE != "{{.AGE_FILE}}" ]]; then
            echo WARNING: SOPS_AGE_KEY_FILE is not set to the expected value, this may cause conflicts.
          fi
      - cmd: |
          if test -f ~/.config/sops/age/keys.txt; then
            echo WARNING: SOPS Age key found in home directory, this may cause conflicts.
          fi
    silent: true
