placeholder: ENC[AES256_GCM,data:nHX59A==,iv:MeW0l3U80a/lD0ewLMihzcl3qzIiEeMTf6KSyA7ClmE=,tag:FqQv/V4JXvpFq/o1NFawFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkqegngtmhgcqqjcxwf58quer37r400dy8mn9t29mg2ngse2uvfq6zd856
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZkhhYVM3TS95cnpUTjdt
            VHl3b2E4dnJjTjNTZnZxbCs0RVhwazlVZWhFCmV3WFVIWUcrWUN5WDk1aDdBcXFB
            U0t2UjRUK3A4R2FjVEZKM2J3bkdFSTgKLS0tIE5RT0kvMk9JeURYQ1JOeWx5LzJE
            QnFUZWdBOVJtTVF2aTBleUhDQXdGNGcK3RuIXm/yPFTqQxg1yvQAu4nKqzamyZ/k
            Tm/hKutP5W1LP0am8hBiJO5zfrSCFUWICDvhl0rMhK+8TjQbdoZgMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T00:05:42Z"
    mac: ENC[AES256_GCM,data:Hp/mkAnDxvs7M0aTM7zN22VwyjgWp+cvBBIdj8MXrog2cbcijme1cg585BjWS/DXCPXDLVme/qmKxTgW1qhhsPjMUQaTqPBA9AiZa3CftXHByrpbMRF+/KUHsycRBBxiEDn2DBXOPZnHzWlu/A+e7VXVO5TEUbjzUsYwIoDXejQ=,iv:nhmai/Oz1UXLP1pBfaYb1Vo6cWJ8ROYQpUbOxfnRVt4=,tag:NlXvBM5mImlTiYjTxeLAAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
