wifi_networks: ENC[AES256_GCM,data:9Wu15FYqGLDUXgIaWH6Dzxcpc1Kkcw498mMqW18kmy9pKVPX6ASbaf64NohI6aVcDDaZTqCURT9Hlb3FF9Wo5wT99+5Bz8D/RaX7HhNWG8wmiSr/W7qNaaTqnXnjZZ8T5mwnf9UiofkgioJFimQQBeYTTqZJ4zj5To5p+H69x66ZL1fJxXdToBBEKQ==,iv:eBvkPjdN2fxQ5tbmntrSpTQz3bJmkFHN6uOYVOXsJcU=,tag:wqmto9uocumFusPg1HtYIg==,type:str]
root:
    password: ENC[AES256_GCM,data:PqabIGAOzsnaA6whVotVvK+CCyMdfbsxnAcP30dMGOeLMF8=,iv:HUmNL/6wjMviDdhUDdS/qyPr+rhbrplle9uI6EmJIo4=,tag:kmx8BY2+0ywVYoT6Uw2Fhw==,type:str]
kevin:
    password: ENC[AES256_GCM,data:3DYMRNn4TjrPEe71,iv:2kNKOnFhKupbJYDOGTB1T5mTt9/cOCUyqE8IvnwPQDM=,tag:s6zSjUzNR9c+7oyIdEyEgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkqegngtmhgcqqjcxwf58quer37r400dy8mn9t29mg2ngse2uvfq6zd856
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbzBmSkcvT2dodmNYWEpU
            Z084ZFhwVUUvU3lORENDSDdMSy9GbW02MWtFCk41RkJGZzg3dkFwMkJPR1Fiemxo
            b1ZqME0yMC9tYW1Ga0RFUE5QdFR1Nm8KLS0tIEZSbkRpeExoM1RlZVlIQzhyTUFv
            V24zUzVMYVhRY1lBYUl2OTBiblNKTFEKI6HhVMQ//aPJGnwUbR+ADvcauVdOqvEN
            rzpR+GkIR2VGZrll1CS6QbqKJ0UsGtkZpOnrzJVT7pVqw4yqgbIcFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T02:31:20Z"
    mac: ENC[AES256_GCM,data:NFnxuwK7oKjZieCuJkqHoy0CR0qhThcZK6g51kVeCUrnewGNe3lHYRXmvIVlK5rCYztO7PP6mjTfyvh6zeooYi6yodMooKDnBVBFoUjeCUUIruZUjD8u77UCdKWXPtgfm8cYo8iLTDnfnEaxx0nLZsn7aIuHn1ZYTF9MsvqUflA=,iv:NplH01HX3zDFVbPYBvZH0R+D76HG5l/iV1Em90kVLRc=,tag:rVVnx2GDQJz3KQZh+LkOBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
