wifi_networks: ENC[AES256_GCM,data:iXFCnoZYtBtI7mJkhhWYu5Cnhdtmma73TYZb8JiLk8FYvaoEFF+l4YxtFSbe7Exx6jmnwPrel7VvpPZIXvXmRukajKUakUf6xTjPWmcbLWJQirCNJd21A3pm0C2Zz8StJK0uh8sMTm3HlVTFKfmgm1M7J5oqnm4sd0AE5CNe7371yMGL1vd1dW77eg==,iv:aIshR5WjvNurqX94c6mHWoPyjjJ7UIe4cMv4GvLch7U=,tag:SQIVRkeqy8444VOcHqb8Mg==,type:str]
root:
    password: ENC[AES256_GCM,data:h4OT46G41yr7q/0zVQ0WdV68wfUFiYffpEdhyIZ+eDPUb8U=,iv:1fw7c2c8dmLeiw18hPWrL6r2RL900vDesXsqZSrFlLI=,tag:cYGa02ddrVBhfX445GVMAQ==,type:str]
kevin:
    password: ENC[AES256_GCM,data:2Dyw8H9dM4zgzVyh,iv:KTbvedmDdtiFLWGXxTuXInDAdFOcJNkO7eqTNqqVJQ0=,tag:cx3GgHpvXWB+mS9/YQxiVA==,type:str]
main_timezone: ENC[AES256_GCM,data:0sxn1CcmVkWw2w054zR/,iv:DGS3vq0idH6Tfk+0tVkTdMqXxnGET22XhrwFa3Be1uo=,tag:pBWksCwJybeQciuzjlpcRQ==,type:str]
main_location: ENC[AES256_GCM,data:4VA84CkCOYtbhF37Bu3/ItPhmf1VoqS96vxXg5UGOPnsZi7JlJpKuF7IoVL/J+axRCW6jmKu,iv:YqnrsEZ0EHDVJR9wstfXKutRZSC4HsmjIP0AcUWR9cU=,tag:LjMh7u8vNEiivF34wPJ6nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkqegngtmhgcqqjcxwf58quer37r400dy8mn9t29mg2ngse2uvfq6zd856
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT0wrQkVBN2ZObEVSbmJC
            OGMrYkd4eGVyWWVDVWhHRHFuVTBCUDRnWkJzCnJTOENURHFtY1Z2cGVGLzg1amVn
            QWRYWmFmbGFjYzEwY1REMDc1VlFKeGsKLS0tIEVOc1M1MFNvdkFoTzJhUVdvcFpH
            bUg0dHc0YVpwQlNGOWdtaklpS2RvdzgK5xhQI30co5KUTzy1uYdjin+3tkMzhzBe
            bjtVAqm3tkmpniOpjEp0kv/uRs9aZ81CQEVhyG/gunUcu1s3/2DN6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T06:38:04Z"
    mac: ENC[AES256_GCM,data:LTI3f6S+mDB08ipsQGVMi/Cc2NYlydXRi6qWQHFug24oF93i9L7Ktrt6eZJCYzl2vzz8W6fOLsS9uoeNU1vJ1/P+q9UVuimyYz3hEi7hPfD2KSMe4QeqVWGwdWYSczcPCZZZlPCYrFwakuHRsldMI5KhRBG0pi91vKrptVzAzlI=,iv:fZD8cD1UMhrzeSJ3ugoEN4YxTNNmw8PzeX3mQv2isLA=,tag:Yk27ldVeSY6EUDNrwaPpNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
